CREATE OR REPLACE VIEW STAFFS_WORKLOAD AS
SELECT S.id Staff_ID,S.name Staff_Name,COUNT(A.id) APPT_COUNTS
FROM Staffs S left join Appointments A
ON S.id = A.staffId
GROUP BY S.id,S.name
ORDER BY APPT_COUNTS DESC;
SELECT * FROM STAFFS_WORKLOAD;

